services:
  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: genesis_test_task
      POSTGRES_USER: vlas
      POSTGRES_PASSWORD: genesis-secret-password55
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vlas -d genesis_test_task"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
